server:
  port: 8085

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nkhatun/config-server
          clone-on-start: true
          default-label: main                    